import type { Metadata } from "next";
import { Yanone_Kaffeesatz } from "next/font/google";
import "./globals.css";



const yanone = Yanone_Kaffeesatz({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-yanone",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${yanone.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
